/* Tile Library:
   Constant int d must
   be defined as the
   dimension of the tile.
*/

const int d=10; // Tile dimension
int b=0; // Background color

void tile(int s[100],int x,int y,int t); // Writes tile s to (x,y) with all
					 // transparent (13) pixels clr t.
int * transform(int s[100],int a,int b); // Changes all pixels in s that
					     // are clr a to clr b.





void tile(int s[100],int x,int y,int t)
{
for (int n=0;n!=d*d;n++);
 {
 }
}

int * transform(int s[100],int a,int b)
{
}